Updated measures data, but it BREAKS the site.
Error: see ticket here:
https://atrium.developmentseed.org/gain/node/37013
/Users/brunosan/Sites/GaIn/gai-gain/views/CountrySummary.bones:11
var trend = indicators.byName('static').trend();
^ TypeError: Cannot call method 'trend' of undefined     at [object
Object].render
(/Users/brunosan/Sites/GaIn/gai-gain/views/CountrySummary.bones:11:49)